# Les Forms fictif pour recevoir les réponses des requêtes envoyés du front #

App\Entity\Announcement:
    properties:
        title :
            - NotBlank: 
                message:  Veuillez entrer un titre.  
            - Type: string 
        body :
            - NotBlank:
                message:  Veuillez entrer un contenu pour l'annonce.  
            - Type: string  


App\Entity\Comment:
    properties:
        body:
            - NotBlank: 
                message:  Veuillez entrer un contenu à votre commentaire.
            - Type: string
            - Length:
                min: 10
                max: 1000
                minMessage: 'Votre commentaire est trop court (10 caractères minimum)'
                maxMessage: 'Votre commentaire est trop long (1000 caractères maximum)'

App\Entity\Tag:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: label
            message: 'Ce tag existe déjà !'
    properties:
        label:
            - NotBlank:
                message:  Veuillez entrer un nom de tag.
            - Type: string
            - Length:
                min: 2
                max: 15
                minMessage: 'Votre label est trop court (2 caractères minimum)'
                maxMessage: 'Votre label est trop long (15 caractères maximum)'
        

App\Entity\Bookmark:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: url
            message: 'Cette url existe déjà !'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: title
            message: 'Ce titre existe déjà !'            
    properties:
        title:
            - NotBlank:
                message:  Veuillez entrer un titre.  
            - Type: string
            - Length:
                min: 10
                max: 100
                minMessage: 'Votre titre est trop court (10 caractères minimum)'
                maxMessage: 'Votre titre est trop long (100 caractères maximum)'
        resume:
            - NotBlank:
                message:  Veuillez entrer un resumé détaillant ce Bookmark.  
            - Type: string
            - Length:
                min: 10
                max: 1000
                minMessage: 'Votre résumé est trop court (10 caractères minimum)'
                maxMessage: 'Votre résumé est trop long (1000 caractères maximum)'
        url:
            - NotBlank :
                message:  Veuillez entrer un lien vers ce bookmark.  
            - Url:
                protocols: [http, https, ftp]
                message: Cette url "{{ value }}"  n'est pas une url valide.
                checkDNS: 'ANY'
                dnsMessage: "Le nom de domaine du lien vers la ressource semble incorrect / inexistant."
            # - Regex:
            #     pattern: '/(http(s)?)://(www.)?a-zA-Z0-9@:%._+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_+.~#?&//=]*)/i'
        published_at:
            - NotBlank: 
                message:  Veuillez entrer la date de création du bookmark. 
            - DateTime: 
                format: yyyy-MM-dd
        author:
            - NotBlank:
                message:  Veuillez entrer le nom de l'auteur (ou provenance) du bookmark.
            - Type: string

App\Entity\User:
    constraints:
        # - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
        #     fields: [ email, pseudo_github ]
        #     errorPath: [ email, pseudo_github ]
        #     message: ' "{{ value }}" existe déjà !'           
    properties:
        first_name:
            - NotBlank:
                message: ' Veuillez entrer un nom '  
            - Type: string 
            - Length:
                min: 2
                minMessage: 'Votre nom doit comporter au moins {{ limit }} caractères.'
        last_name:
            - NotBlank: 
                message: ' Veuillez entrer un prénom ' 
            - Type: string
            - Length:
                min: 2
                minMessage: Votre prénom doit comporter au moins {{ limit }} caractères.
        email:
            - NotBlank: 
                message: ' Veuillez entrer un email ' 
            - Email: 
                message: L'email {{ value }} , n'est pas un email valide.
                checkHost: true
            # - Regex:
            #     pattern: '!/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i]'
        birthday:
            - NotBlank:
                message: ' Veuillez entrer une date de naissance ' 
            - DateTime: 
                format: yyyy-MM-dd
                message: La date de naissance "{{ value }}" n'est pas valide.
        pseudo_github:
            - NotBlank:
                message: ' Veuillez entrer un pseudo Github ' 
            - Type: string  
        zip:
            - NotBlank:
                message: ' Veuillez entrer un code postal '
            - Length:
                min: 4
                minMessage: Votre code postal doit comporter au moins {{ limit }} caractères.
                max: 10
                maxMessage: Votre code postal doit comporter au maximum {{ limit }} caractères.
        #password:
        #     - Symfony\Component\Security\Core\Validator\Constraints\UserPassword:
        #         message: Votre ancien mot de passe n'est pas le bon 
        #     - Type: 
        #         type: string
        #     - Range:
        #         max: 8
        #         maxMessage: Votre mot de passe doit comporter au maximum {{ limit }} caractères.
                  
App\Entity\Vote:
    # constraints:
    #      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
    properties:
        value:
            - NotBlank: 
                message:  Veuillez entrer une note
            - Type: integer
            - Range:
                min: -1
                max: 1
                minMessage: Votre note ne doit pas être en dessous de -1.
                maxMessage: Votre note ne doit pas dépasser 1.
            

        